language: php

sudo: false

php:
  - 5.6

services:
  - mysql

before_install:
  - nvm install 7
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install --no-interaction --prefer-source
  - npm install autoprefixer node-sass postcss postcss-cli

before_script:
  - mysql -u root -e 'CREATE DATABASE testing;'
  - mysql -u root -e "CREATE USER 'testing'@'127.0.0.1' IDENTIFIED BY 'testing';"
  - mysql -u root -e "GRANT ALL ON testing.* TO 'testing'@'127.0.0.1';"
  - mysql -u root testing < data/database.sql
  - php vendor/bin/phinx migrate -e testing

script:
  - php vendor/bin/tester -p php -c ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini tests/cases

after_failure:
  # Print *.actual content
  - 'for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

cache:
  directories:
    - $HOME/.composer/cache
