language: php

sudo: false

php:
  - 5.6

services:
  - mysql

install:
  - composer install --no-interaction --prefer-source

before_script:
  - mysql -u root -e 'CREATE DATABASE testing;'
  - mysql -u root -e "CREATE USER 'testing'@'127.0.0.1' IDENTIFIED BY 'testing';"
  - mysql -u root -e "GRANT ALL ON testing.* TO 'testing'@'127.0.0.1';"
  - mysql -u root testing < data/database.sql
  - php vendor/bin/phinx migrate -e testing

script:
  #- php vendor/bin/tester -p php -c tests/php.ini tests/cases
  - php vendor/bin/tester -p php tests/cases

after_failure:
  # Print *.actual content
  - 'for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

cache:
  directories:
    - $HOME/.composer/cache
